---
- name: Deploy Applications Online revive Service
  become: yes
  hosts: sandbox
  user: jenkins

  vars:
    env: sandbox
    env_prefix: ds

  roles:
    - bootstrap-user
    - cmg-ansible-role-filebeat # Needs this in order to restart filebeat
    - cmg-ansible-role-cloudwatch-logs
    - cmg-ansible-role-logrotate
    - cmg-ansible-role-firewalld
    - cmg-ansible-role-ssl-certs
    - cmg-ansible-role-s3-yumrepo
    - cmg-ansible-role-nodejs
    - cmg-ansible-role-prometheus-rpm
    - cmg-ansible-role-clamav-scan

  tasks:
    - name: Include shared tasks
      include: './tasks/main.yml'
