---
- name: Deploy Applications Online revive Service
  become: yes
  hosts: test
  user: jenkins

  vars:
    env: test
    env_prefix: dt

  roles:
    # - bootstrap-user
    # - cmg-ansible-role-filebeat # Needs this in order to restart filebeat
    # - cmg-ansible-role-cloudwatch-logs
    # - cmg-ansible-role-logrotate
    # - cmg-ansible-role-firewalld
    # - cmg-ansible-role-ssl-certs
    # - cmg-ansible-role-s3-yumrepo
    # - cmg-ansible-role-prometheus-rpm
    # - cmg-ansible-role-clamav-scan
    - cmg-ansible-role-tomcat

  tasks:
    - name: Include shared tasks
      include: './tasks/main.yml'
